# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3491816c91fe1c9064e0acbf852f69e33af95d9456c4546b9f4f4b95c6caa48ef8ff17c43ad6fbae9a36df0509a12e1f23ee2b2687a1ec2eb1d4e4a10f6bd069

test:
  secret_key_base: ac643819fa2b0c57f9950136ac56d9a87ed05356ca40fa0131cac3332ceb67ce7b8348a77842b6040fd55219485ef5fd9bd053e3e77cb76113d6ac14fde08633

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
